--- # Required Testnet Parameters
poolCount: 60
poolCost: 340000000
poolMargin: 0.0
poolPledge: 0
delegatedSupply: 600000000000000
systemStart: '2025-03-27T08:18:06Z'
systemStartDelay: 0
networkMagic: 43
testnetDomain: testnet.local.net
--- # Optional Byron Genesis Overide
--- # Optional Shelley Genesis Overide
protocolParams:
  decentralisationParam: 0
  protocolVersion:
    major: 10
    minor: 0
securityParam: 12
epochLength: 500
activeSlotsCoeff: 1.0
slotLength: 1
slotsPerKESPeriod: 129600

--- # Optional Alonzo Genesis Overide
--- # Optional Conway Genesis Overide
--- # Optional Node Config Overide
TestShelleyHardForkAtEpoch: 0
TestAllegraHardForkAtEpoch: 0
TestMaryHardForkAtEpoch: 0
TestAlonzoHardForkAtEpoch: 0
TestBabbageHardForkAtEpoch: 0
TestConwayHardForkAtEpoch: 0
LastKnownBlockVersion-Alt: 0
LastKnownBlockVersion-Major: 6
LastKnownBlockVersion-Minor: 0
MaxKnownMajorProtocolVersion: 2
ExperimentalProtocolsEnabled: true
ExperimentalHardForksEnabled: true
